# You can build all images with docker compose build


services:

# Original image, vulnerabilities included
# Build this image alone with "docker compose up nodeapp --build" OR
  nodeapp:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 80:3000

# Hardened image
# Build this image alone with "docker compose up nodeapp-dhi --build"
  nodeapp-dhi:
    build:
      context: .
      dockerfile: Dockerfile.dhi
    environment:
      NODE_ENV: production
    ports:
      - 80:3000

# Hardened image with multi-stage build.
# Build this image alone with "docker compose up nodeapp-multidhi --build"
  nodeapp-multidhi:
    build:
      context: .
      dockerfile: Dockerfile.multidhi
    environment:
      NODE_ENV: production
    ports:
      - 80:3000

