name: Pipeline using GitHub Actions with Matrix Strategy

# This workflow handles multiple Dockerfile variants with enhanced error handling
# for Docker Scout recommendations that may fail on certain base images

on:
  push:
    branches:
      - main
    tags: 
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            variant: ""
            context: .
          - dockerfile: Dockerfile.dhi
            variant: "-dhi"
            context: .
          - dockerfile: Dockerfile.multidhi
            variant: "-multidhi"
            context: .
    outputs:
      IMAGE_TAGS: ${{ toJSON( fromJSON(steps.meta.outputs.json).tags ) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Environment Variables
        uses: ./.github/workflows/load-env

      - name: Set up containerd
        uses: docker/setup-docker-action@v4.3
        with:
          set-host: true
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image tags and labels
        id: meta
        uses: docker/metadata-action@v5.7
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_PREFIX }}${{ env.IMAGE_NAME }}${{ matrix.variant }}-gha
          tags: |
            type=ref,enable=true,event=branch,suffix=--{{sha}}
            type=ref,enable=true,event=branch,suffix=--latest
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          provenance: mode=max
          sbom: true
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1.18.1
        with:
          command: cves
          image: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
          organization: ${{ env.DOCKERHUB_NAMESPACE }}
          exit-on: vulnerability, policy
          summary: true

      - name: Get Docker Scout recommendations
        id: docker-scout-recommendations
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1.18.1
        with:
          command: recommendations
          image: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
          organization: ${{ env.DOCKERHUB_NAMESPACE }}
          summary: true
        continue-on-error: true